<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModeleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("modeles")->insert([
            ["nom"=> "P196HQV"],
            ["nom"=> "Travelmate 7720"],
            ["nom"=> "OS6450-P48 cuivre"],
            ["nom"=> "AOC"],
            ["nom"=> "RS1200"],
            ["nom"=> "800"],
            ["nom"=> "10KVA"],
            ["nom"=> "LIDE110" ],
            ["nom"=> "ADSL"],
            ["nom"=> "600av"],
            ["nom"=> "Alphapower"],
            ["nom"=> "9009S"],
            ["nom"=> "core i3"],
            ["nom"=> "duel core e5500"],
            ["nom"=> "M2400HL"],
            ["nom"=> "E2214HB"],
            ["nom"=> "N3024F Optique"],
            ["nom"=> "Optiplex 9020"],
            ["nom"=> "7029-6E3"],
            ["nom"=> "Eserie NV"],
            ["nom"=> "5E1100"],
            ["nom"=> "EX2200"],
            ["nom"=> "Eserie NV"],
           
            ["nom"=> "9130"],
            ["nom"=> "ATLAS 1250"],
            ["nom"=> "TM-T88V"],
            ["nom"=> "Display B24_8TE-LED"],
            ["nom"=> "L22T-6"],
            ["nom"=> "ESPRIMO P957 E85"],
            ["nom"=> "DL3750+"],
            ["nom"=> "Celius M730n"],
            ["nom"=> "L22T-6"],
            ["nom"=> "LIFEBOOK"],
            ["nom"=> "Esprimo P758 E94+N"],
            ["nom"=> "Display B22-8TS LCD"],
            ["nom"=> "Esprimo P3520"],
            ["nom"=> "Display DY22-8T LCD"],
            ["nom"=> "LA36N"],
            ["nom"=> "dx 7300"],
            ["nom"=> "L1706"],
            ["nom"=> "elite 8300"],
            ["nom"=> "W1972a"],
            ["nom"=> "1300"],
            ["nom"=> "W1972a"],
            ["nom"=> "P1005"],
            ["nom"=> "P1102"],
            ["nom"=> "Prodisplay P223-21,5"],
            ["nom"=> "dx 2200"],
            ["nom"=> "3600"],
            ["nom"=> "2500cm"],
            ["nom"=> "MP3222"],
            ["nom"=> "Designjet 800"],
            ["nom"=> "Designjet 450"],
            ["nom"=> "Pro Desk 600G4"],
            ["nom"=> "Prodesk 600G4"],
            ["nom"=> "X1 1000"],
            ["nom"=> "1250 IEC"],
            ["nom"=> "RT2000"],
            ["nom"=> "FS1016MFP"],
            ["nom"=> "FS1025MFP"],
            ["nom"=> "FS1118MFP"],
            ["nom"=> "MS 8520"],
            ["nom"=> "ECOSYS M2030 MFD DN"],
            ["nom"=> "UPS Draker dk"],
            ["nom"=> "E340"],
            ["nom"=> "2391"],
            ["nom"=> "2400 series"],
            ["nom"=> "MS510dn"],
            ["nom"=> "MX310DN"],
            ["nom"=> "E260dn"],
            ["nom"=> "MX310"],
            ["nom"=> "MS310"],
            ["nom"=> "X463"],
            ["nom"=> "2590 series"],
            ["nom"=> "MX710de"],
            ["nom"=> "X740"],
            ["nom"=> "MX510"],
            ["nom"=> "MS415DN"],
            ["nom"=> "2591 series"],
            ["nom"=> "C748de"],
            ["nom"=> "CX860 de couleur A4"],
            ["nom"=> "B930n"],
            ["nom"=> "B411dn"],
            ["nom"=> "B6250"],
            ["nom"=> "KX-MB1900"],
            ["nom"=> "ML3310ND"],
            ["nom"=> "CLP620dn"],
            ["nom"=> "ML3710ND"],
            ["nom"=> "CLP775nd"],
            ["nom"=> "C600"],
            ["nom"=> "phaser 3330"],
            ["nom"=> "Copy center"],
            ["nom"=> "versalink B605"],
            ["nom"=> "3425 Phaser"],
            ["nom"=> "B400"],
            ["nom"=> "Phaser 3610"],
            ["nom"=> "portable DS 2200"],
            ["nom"=> "GX420T"],
            
            ]);

    }
}
